server:
  port: 8081
spring:
  application:
    name: patient-service
  datasource:
    username: test
    password: test
    url: jdbc:mariadb://localhost:3306/testdemo
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
